networks:
  mt5_net:
    name: mt5_net

services:
  mt5:
    image: gmag11/metatrader5_vnc:latest
    platform: linux/amd64
    container_name: mt5
    volumes:
      - ./config:/config
      - ./Metatrader/start.sh:/Metatrader/start.sh:ro
      - ./Metatrader/experts:/config/.wine/drive_c/Program Files/MetaTrader 5/MQL5/Experts/MT5Bridge
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:8001:8001
    env_file:
      - .env
    networks:
      - mt5_net
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  bridge:
    build:
      context: ./src
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: mt5_bridge
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - MT5_TCP_PORT=9000
      - HTTP_PORT=8080
    networks:
      - mt5_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

